'use client';

import { useState, useCallback } from 'react';
import { Scenario, TranscriptEntry, NpcResponse, VotingOption } from '../lib/types';
import SessionAnalysis from './SessionAnalysis';

interface VerdictProps {
  scenario: Scenario;
  transcript: TranscriptEntry[];
  npcResponses: NpcResponse[];
  votingOptions: VotingOption[];
}

type ExportFormat = 'report' | 'transcript' | 'participation' | 'json';

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function fmtTime(ts: number) {
  return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

export default function Verdict({
  scenario,
  transcript,
  npcResponses,
  votingOptions,
}: VerdictProps) {
  const [showHistorical, setShowHistorical] = useState(false);
  const [showSave, setShowSave] = useState(false);
  const [showAnalysis, setShowAnalysis] = useState(false);
  const [lastExported, setLastExported] = useState<ExportFormat | null>(null);

  const totalVotes = votingOptions.reduce((sum, o) => sum + o.votes, 0);
  const sorted = [...votingOptions].sort((a, b) => b.votes - a.votes);
  const winner = sorted[0];
  const isTie = sorted.length > 1 && sorted[0].votes === sorted[1].votes && sorted[0].votes > 0;
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const slug = scenario.title.replace(/\s+/g, '_').replace(/[^\w]/g, '');

  const buildReport = useCallback(() => {
    const lines: string[] = [
      `${'='.repeat(60)}`,
      `  ${scenario.title.toUpperCase()}`,
      `  ${scenario.setting}`,
      `  Session Report — ${dateStr}`,
      `${'='.repeat(60)}`,
      '',
      'CENTRAL QUESTION',
      scenario.centralQuestion,
      '',
    ];

    if (totalVotes > 0) {
      lines.push('VOTE RESULTS', '-'.repeat(40));
      for (const o of [...votingOptions].sort((a, b) => b.votes - a.votes)) {
        const pct = totalVotes > 0 ? ((o.votes / totalVotes) * 100).toFixed(0) : '0';
        const bar = '█'.repeat(Math.round((o.votes / Math.max(totalVotes, 1)) * 20));
        lines.push(`  ${o.label}: ${o.votes} votes (${pct}%)  ${bar}`);
      }
      lines.push(`  Total: ${totalVotes} votes`, '');
    }

    if (transcript.length > 0) {
      lines.push('ARGUMENTS & DISCUSSION', '-'.repeat(40));
      for (const e of transcript) {
        lines.push(`  [${fmtTime(e.timestamp)}] ${e.speaker}:`);
        lines.push(`  ${e.text}`, '');
      }
    }

    if (npcResponses.length > 0) {
      lines.push('NPC RESPONSES', '-'.repeat(40));
      for (const r of npcResponses) {
        const npc = scenario.npcs.find((n) => n.id === r.npcId);
        lines.push(`  ${npc?.name || r.npcId} (${npc?.title || ''}):`);
        lines.push(`  ${r.text}`, '');
      }
    }

    lines.push(
      'OUTCOME', '-'.repeat(40),
      scenario.outcome || '(No outcome provided)',
      '',
      `${'='.repeat(60)}`,
      `  Generated by Historical Roleplaying Helper`,
      `${'='.repeat(60)}`,
    );
    return lines.join('\n');
  }, [scenario, transcript, npcResponses, votingOptions, totalVotes, dateStr]);

  const buildTranscript = useCallback(() => {
    const lines: string[] = [
      `${scenario.title} — Raw Transcript`,
      `${dateStr}`,
      '',
    ];
    for (const e of transcript) {
      lines.push(`[${fmtTime(e.timestamp)}] ${e.speaker}: ${e.text}`);
    }
    if (npcResponses.length > 0) {
      lines.push('', '--- NPC ---', '');
      for (const r of npcResponses) {
        const npc = scenario.npcs.find((n) => n.id === r.npcId);
        lines.push(`[${fmtTime(r.timestamp)}] ${npc?.name || r.npcId}: ${r.text}`);
      }
    }
    return lines.join('\n');
  }, [scenario, transcript, npcResponses, dateStr]);

  const buildParticipation = useCallback(() => {
    const speakers = new Map<string, { count: number; totalChars: number; entries: string[] }>();
    for (const e of transcript) {
      const s = speakers.get(e.speaker) || { count: 0, totalChars: 0, entries: [] };
      s.count++;
      s.totalChars += e.text.length;
      s.entries.push(e.text);
      speakers.set(e.speaker, s);
    }

    const lines: string[] = [
      `${scenario.title} — Participation Log`,
      `${dateStr}`,
      '',
      `Total contributions: ${transcript.length}`,
      `Unique speakers: ${speakers.size}`,
      '',
      'SPEAKER BREAKDOWN',
      '-'.repeat(40),
    ];

    const sorted = [...speakers.entries()].sort((a, b) => b[1].count - a[1].count);
    for (const [name, data] of sorted) {
      lines.push(`  ${name}: ${data.count} contributions (~${Math.round(data.totalChars / data.count)} chars avg)`);
      for (const entry of data.entries) {
        lines.push(`    • ${entry.length > 120 ? entry.slice(0, 120) + '...' : entry}`);
      }
      lines.push('');
    }

    if (totalVotes > 0) {
      lines.push('VOTE RESULTS', '-'.repeat(40));
      for (const o of votingOptions) {
        lines.push(`  ${o.label}: ${o.votes}`);
      }
    }
    return lines.join('\n');
  }, [scenario, transcript, votingOptions, totalVotes, dateStr]);

  const handleExport = useCallback((format: ExportFormat) => {
    switch (format) {
      case 'report':
        downloadFile(buildReport(), `${slug}_report.txt`, 'text/plain');
        break;
      case 'transcript':
        downloadFile(buildTranscript(), `${slug}_transcript.txt`, 'text/plain');
        break;
      case 'participation':
        downloadFile(buildParticipation(), `${slug}_participation.txt`, 'text/plain');
        break;
      case 'json':
        downloadFile(JSON.stringify({
          scenario,
          transcript,
          npcResponses,
          votingOptions,
          exportedAt: new Date().toISOString(),
        }, null, 2), `${slug}_data.json`, 'application/json');
        break;
    }
    setLastExported(format);
    setTimeout(() => setLastExported(null), 2000);
  }, [slug, scenario, transcript, npcResponses, votingOptions, buildReport, buildTranscript, buildParticipation]);

  const exportOptions: { id: ExportFormat; label: string; desc: string; icon: string }[] = [
    { id: 'report', label: 'Session Report', desc: 'Formatted overview with votes, arguments, NPC responses, and historical outcome', icon: '📄' },
    { id: 'transcript', label: 'Raw Transcript', desc: 'Timestamped log of everything said, by students and NPCs', icon: '📝' },
    { id: 'participation', label: 'Participation Log', desc: 'Per-speaker breakdown with contribution counts and summaries', icon: '👥' },
    { id: 'json', label: 'Raw Data (JSON)', desc: 'Machine-readable export of all session data', icon: '{ }' },
  ];

  return (
    <div className="relative mx-auto max-w-3xl">
      {/* Full-viewport background image, subtle backdrop */}
      {scenario.backgroundImage && (
        <div
          className="pointer-events-none fixed inset-0 animate-in"
          style={{ zIndex: 0 }}
        >
          <div
            className="absolute inset-0"
            style={{
              backgroundImage: `url(${scenario.backgroundImage})`,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              opacity: 0.18,
            }}
          />
          <div
            className="absolute inset-0"
            style={{
              background: `linear-gradient(
                to bottom,
                var(--background) 0%,
                transparent 40%,
                transparent 70%,
                var(--background) 100%
              )`,
            }}
          />
        </div>
      )}

      <div className="relative space-y-6" style={{ zIndex: 1 }}>
        {/* Vote Results Summary */}
        {totalVotes > 0 && (
          <div className="glass animate-in-scale rounded-2xl p-8 text-center">
            <p className="mb-1 text-sm uppercase tracking-widest" style={{ color: 'var(--text-muted)' }}>
              {isTie ? 'The Result' : 'The Decision'}
            </p>
            {isTie ? (
              <>
                <p className="heading-display text-4xl font-bold" style={{ color: 'var(--accent)' }}>
                  Tied Vote
                </p>
                <p className="mt-2 text-base" style={{ color: 'var(--text-secondary)' }}>
                  {sorted.filter((o) => o.votes === winner.votes).map((o) => o.label).join(' vs. ')} — {winner.votes} votes each
                </p>
              </>
            ) : (
              <>
                <p className="heading-display text-4xl font-bold" style={{ color: 'var(--accent)' }}>
                  {winner.label}
                </p>
                <p className="mt-2 text-base" style={{ color: 'var(--text-secondary)' }}>
                  {winner.votes} of {totalVotes} votes ({((winner.votes / totalVotes) * 100).toFixed(0)}%)
                </p>
              </>
            )}
          </div>
        )}

        {/* Session Stats — clickable to expand analysis */}
        <div
          className="glass rounded-2xl p-6 transition-all cursor-pointer hover:border-[rgba(212,160,60,0.25)]"
          onClick={() => setShowAnalysis((s) => !s)}
        >
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold uppercase tracking-widest" style={{ color: 'var(--text-muted)' }}>
              Session Summary
            </h3>
            <span className="text-xs" style={{ color: 'var(--text-muted)' }}>
              {showAnalysis ? 'Click to collapse' : 'Click for detailed analysis'}
            </span>
          </div>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <p className="font-mono text-3xl font-bold" style={{ color: 'var(--accent)' }}>{transcript.length}</p>
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Arguments</p>
            </div>
            <div>
              <p className="font-mono text-3xl font-bold" style={{ color: 'var(--accent)' }}>{npcResponses.length}</p>
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>NPC Responses</p>
            </div>
            <div>
              <p className="font-mono text-3xl font-bold" style={{ color: 'var(--accent)' }}>{totalVotes}</p>
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Votes Cast</p>
            </div>
          </div>
          {showAnalysis && (
            <div className="mt-6 pt-5" style={{ borderTop: '1px solid var(--panel-border)' }} onClick={(e) => e.stopPropagation()}>
              <SessionAnalysis
                transcript={transcript}
                stages={scenario.stages}
                votingOptions={votingOptions}
              />
            </div>
          )}
        </div>

        {/* Outcome Reveal */}
        {scenario.outcome && (
          <>
            <div className="text-center">
              <button
                onClick={() => setShowHistorical(!showHistorical)}
                className="heading-display rounded-2xl px-10 py-5 text-2xl font-bold transition-all hover:scale-[1.02]"
                style={{
                  background: showHistorical
                    ? 'rgba(255,255,255,0.06)'
                    : 'linear-gradient(135deg, rgba(212,160,60,0.3), rgba(180,120,40,0.2))',
                  color: 'var(--accent)',
                  border: '1px solid rgba(212,160,60,0.25)',
                  boxShadow: showHistorical ? 'none' : '0 0 40px rgba(212,160,60,0.1)',
                }}
              >
                {showHistorical ? 'Hide Outcome' : 'Reveal: What Actually Happened'}
              </button>
            </div>

            {showHistorical && (
              <div
                className="animate-in-scale rounded-2xl p-8"
                style={{
                  background: 'linear-gradient(135deg, rgba(212,160,60,0.08), rgba(15,17,23,0.9))',
                  border: '2px solid rgba(212,160,60,0.2)',
                }}
              >
                <h3
                  className="heading-display mb-4 text-center text-2xl font-bold"
                  style={{ color: 'var(--accent)' }}
                >
                  The Outcome
                </h3>
                <p className="text-lg leading-relaxed" style={{ color: 'var(--text-primary)' }}>
                  {scenario.outcome}
                </p>
              </div>
            )}
          </>
        )}

        {/* Save Session */}
        <div className="pt-2 text-center">
          <button
            onClick={() => setShowSave(!showSave)}
            className="heading-display rounded-2xl px-8 py-4 text-xl font-semibold transition-all hover:scale-[1.02]"
            style={{
              background: showSave ? 'rgba(255,255,255,0.06)' : 'rgba(99,182,255,0.1)',
              color: showSave ? 'var(--text-secondary)' : '#7db8f0',
              border: `1px solid ${showSave ? 'rgba(255,255,255,0.08)' : 'rgba(99,182,255,0.2)'}`,
            }}
          >
            {showSave ? 'Hide Export Options' : 'Save Session'}
          </button>
        </div>

        {showSave && (
          <div className="animate-in space-y-3">
            <p className="text-center text-sm" style={{ color: 'var(--text-muted)' }}>
              Choose a format to download
            </p>
            <div className="grid gap-3 sm:grid-cols-2">
              {exportOptions.map((opt) => {
                const justExported = lastExported === opt.id;
                return (
                  <button
                    key={opt.id}
                    onClick={() => handleExport(opt.id)}
                    className="glass group flex items-start gap-4 rounded-xl p-4 text-left transition-all hover:scale-[1.01] hover:border-[rgba(212,160,60,0.25)]"
                  >
                    <span className="mt-0.5 text-2xl">{justExported ? '✓' : opt.icon}</span>
                    <div className="flex-1 min-w-0">
                      <p className="text-base font-semibold" style={{ color: justExported ? '#6ee7b7' : 'var(--text-primary)' }}>
                        {justExported ? 'Downloaded!' : opt.label}
                      </p>
                      <p className="mt-0.5 text-sm leading-snug" style={{ color: 'var(--text-muted)' }}>
                        {opt.desc}
                      </p>
                    </div>
                    <span
                      className="mt-1 text-sm opacity-0 transition-opacity group-hover:opacity-100"
                      style={{ color: 'var(--accent)' }}
                    >
                      ↓
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
